[package]
name = "shield-circuit"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sha3 = "0.10.8"
rand = "0.8.5"
hex = "0.4.3"
